//COMMAND: This guess the number game is a short TypeScript/Node.js project that allows the user to guess the number generated by the computer. There are also several ways to alter the game, like adding more rounds or displaying the score. It’s quite simple and uses the random function to generate a number.

import inquirer from "inquirer"
let Random_Number : Number = Math.floor((Math.random()*9)+1);
let userInput = await inquirer.prompt({
    type: "number",
    name: "Guessed_Number",
    message:"Guess the number Between 1-9"
})
if (Random_Number===userInput.Guessed_Number){
    console.log("Congratulation You earned 10 Points")
}
else{
    console.log(`"Game Over", Correct Answer${Random_Number}`)
}
